# -*- coding: utf-8 -*-
"""RiemannSurfaces.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1byck6G0d6pkPSGJN0wNpxCzsir0xxbA3
"""

!sudo apt update
!sudo apt install -y ffmpeg libcairo2-dev libpango1.0-dev texlive texlive-latex-extra texlive-fonts-recommended texlive-xetex

!pip install manim
print("✅ Installation complete!")

from manim import *
import numpy as np

# ── Font constants — one place to change the whole look ──────────────────────
NOTE_FONT   = "Arial"          # wide, legible sans-serif on dark backgrounds
NOTE_SIZE   = 21               # up from 18-19
NOTE_COLOR  = "#c8cce8"        # slightly brighter than old #aaaacc
NOTE_STROKE = 0.45             # gives glyphs body on the dark bg
HDR_STROKE  = 0.5


class RiemannSurfaces(ThreeDScene):
    def construct(self):
        self.camera.background_color = "#070712"

        # ══════════════════════════════════════════════════════════════════
        # PART 0 — TITLE CARD
        # ══════════════════════════════════════════════════════════════════
        self.set_camera_orientation(phi=0, theta=-PI / 2)

        title = Text("Riemann Surfaces", font_size=54, color="#00e5ff",
                     weight=BOLD, font=NOTE_FONT, stroke_width=HDR_STROKE)
        subtitle = Text(
            "What happens when a function has multiple values?",
            font_size=23, color=NOTE_COLOR,
            font=NOTE_FONT, stroke_width=NOTE_STROKE,
        )
        subtitle.next_to(title, DOWN, buff=0.46)
        dec = Line(
            title.get_left(), title.get_right(),
            color="#ff9944", stroke_width=2,
        ).next_to(title, DOWN, buff=0.18)
        author = Text(
            "Complex analysis  ·  Bernhard Riemann  ·  1851",
            font_size=17, color="#555577",
            font=NOTE_FONT, stroke_width=0.3,
        )
        author.to_edge(DOWN, buff=0.4)

        self.add_fixed_in_frame_mobjects(title)
        self.play(Write(title), run_time=1.8)
        self.add_fixed_in_frame_mobjects(dec)
        self.play(Create(dec), run_time=0.5)
        self.add_fixed_in_frame_mobjects(subtitle)
        self.play(FadeIn(subtitle, shift=UP * 0.2), run_time=0.9)
        self.add_fixed_in_frame_mobjects(author)
        self.play(FadeIn(author), run_time=0.6)
        self.wait(3.0)
        self.play(FadeOut(title), FadeOut(dec), FadeOut(subtitle), FadeOut(author), run_time=0.7)
        self.remove(title, dec, subtitle, author)

        # ══════════════════════════════════════════════════════════════════
        # PART 1 — THE COMPLEX PLANE
        # ══════════════════════════════════════════════════════════════════
        lbl1 = Text("Step 1  —  The Complex Plane",
                    font_size=27, color="#00e5ff", weight=BOLD,
                    font=NOTE_FONT, stroke_width=HDR_STROKE)
        lbl1.to_edge(UP, buff=0.45)
        self.add_fixed_in_frame_mobjects(lbl1)
        self.play(FadeIn(lbl1), run_time=0.5)

        plane = NumberPlane(
            x_range=[-4.5, 4.5, 1], y_range=[-3.2, 3.2, 1],
            background_line_style={"stroke_color": "#1a1a3a", "stroke_width": 1, "stroke_opacity": 0.75},
            axis_config={"stroke_color": "#2a2a5a", "stroke_width": 1.5},
        )
        x_lbl = Text("Real  →", font_size=17, color="#555577", font=NOTE_FONT)
        x_lbl.to_edge(RIGHT, buff=0.25).shift(DOWN * 0.25)
        y_lbl = Text("Imaginary  ↑", font_size=17, color="#555577", font=NOTE_FONT)
        y_lbl.rotate(PI / 2)
        y_lbl.to_edge(UP, buff=0.5).shift(LEFT * 4.0)

        self.add_fixed_in_frame_mobjects(plane, x_lbl, y_lbl)
        self.play(FadeIn(plane), FadeIn(x_lbl), FadeIn(y_lbl), run_time=1.2)

        z_dot  = Dot([2, 1.5, 0], color=YELLOW, radius=0.13)
        r_dash = DashedLine([0, 0, 0], [2, 0, 0],   color="#ffdd00", stroke_width=2)
        i_dash = DashedLine([2, 0, 0], [2, 1.5, 0], color="#ff4488", stroke_width=2)
        z_lbl  = Text("z = 2 + 1.5i", font_size=22, color=YELLOW,
                      font=NOTE_FONT, stroke_width=0.35)
        z_lbl.next_to(z_dot, UR, buff=0.14)
        r_lbl = Text("2  (real part)", font_size=17, color="#ffdd00",
                     font=NOTE_FONT, stroke_width=0.3)
        r_lbl.next_to([1, 0, 0], DOWN, buff=0.18)
        i_lbl = Text("1.5i  (imaginary part)", font_size=17, color="#ff4488",
                     font=NOTE_FONT, stroke_width=0.3)
        i_lbl.next_to([2.6, 0.75, 0], RIGHT, buff=0.1)

        self.add_fixed_in_frame_mobjects(r_dash, r_lbl)
        self.play(Create(r_dash), FadeIn(r_lbl), run_time=0.8)
        self.add_fixed_in_frame_mobjects(i_dash, i_lbl)
        self.play(Create(i_dash), FadeIn(i_lbl), run_time=0.8)
        self.add_fixed_in_frame_mobjects(z_dot, z_lbl)
        self.play(FadeIn(z_dot, scale=1.8), FadeIn(z_lbl), run_time=0.6)

        note1 = Text(
            "Every complex number  z = x + iy  is a point on this 2D plane",
            font_size=NOTE_SIZE, color=NOTE_COLOR,
            font=NOTE_FONT, stroke_width=NOTE_STROKE,
        )
        note1.to_edge(DOWN, buff=0.45)
        self.add_fixed_in_frame_mobjects(note1)
        self.play(FadeIn(note1), run_time=0.6)
        self.wait(2.8)

        self.play(*[FadeOut(m) for m in [
            plane, x_lbl, y_lbl, z_dot, r_dash, i_dash, z_lbl, r_lbl, i_lbl, note1, lbl1,
        ]], run_time=0.8)
        self.remove(plane, x_lbl, y_lbl, z_dot, r_dash, i_dash, z_lbl, r_lbl, i_lbl, note1, lbl1)

        # ══════════════════════════════════════════════════════════════════
        # PART 2 — THE MULTI-VALUE PROBLEM
        # ══════════════════════════════════════════════════════════════════
        lbl2 = Text("Step 2  —  The Problem:  every z has TWO square roots",
                    font_size=24, color="#ff9944", weight=BOLD,
                    font=NOTE_FONT, stroke_width=HDR_STROKE)
        lbl2.to_edge(UP, buff=0.45)
        self.add_fixed_in_frame_mobjects(lbl2)
        self.play(FadeIn(lbl2), run_time=0.5)

        plane2 = NumberPlane(
            x_range=[-3.8, 3.8, 1], y_range=[-2.8, 2.8, 1],
            background_line_style={"stroke_color": "#1a1a3a", "stroke_width": 1, "stroke_opacity": 0.55},
        )
        self.add_fixed_in_frame_mobjects(plane2)
        self.play(FadeIn(plane2), run_time=0.8)

        # ── Three dots on the real axis ───────────────────────────────────
        z_main = Dot([2, 0, 0],            color=YELLOW,    radius=0.12)
        sq_pos = Dot([np.sqrt(2), 0, 0],   color="#00ffcc", radius=0.11)
        sq_neg = Dot([-np.sqrt(2), 0, 0],  color="#ff4488", radius=0.11)

        # Labels all go UP — staggered so none overlap each other
        lz  = Text("z = 2",          font_size=19, color=YELLOW,
                   font=NOTE_FONT, stroke_width=0.35)
        lsp = Text("+√2  ≈  +1.41",  font_size=19, color="#00ffcc",
                   font=NOTE_FONT, stroke_width=0.35)
        lsn = Text("−√2  ≈  −1.41",  font_size=19, color="#ff4488",
                   font=NOTE_FONT, stroke_width=0.35)
        lz.next_to(z_main,  UP, buff=0.22).shift(RIGHT * 0.15)
        lsp.next_to(sq_pos, UP, buff=0.22).shift(LEFT  * 0.20)
        lsn.next_to(sq_neg, UP, buff=0.22)

        # Reveal one at a time — register each right before its own FadeIn
        self.add_fixed_in_frame_mobjects(z_main, lz)
        self.play(FadeIn(z_main, scale=1.6), FadeIn(lz), run_time=0.6)
        self.wait(0.4)

        self.add_fixed_in_frame_mobjects(sq_pos, lsp)
        self.play(FadeIn(sq_pos, scale=1.6), FadeIn(lsp), run_time=0.6)
        self.wait(0.3)

        self.add_fixed_in_frame_mobjects(sq_neg, lsn)
        self.play(FadeIn(sq_neg, scale=1.6), FadeIn(lsn), run_time=0.6)
        self.wait(0.4)

        # NOTE 1 — "Two valid answers"
        note_two = Text("Two valid answers — which do we pick?",
                        font_size=NOTE_SIZE, color="#ff9944",
                        font=NOTE_FONT, stroke_width=NOTE_STROKE)
        note_two.to_edge(DOWN, buff=0.5)
        self.add_fixed_in_frame_mobjects(note_two)
        self.play(FadeIn(note_two), run_time=0.5)
        self.wait(1.8)

        # ── Clear everything before drawing the orbit circle ──────────────
        # Every dot, label, and the bottom note — nothing left on the graph
        self.play(
            FadeOut(z_main), FadeOut(lz),
            FadeOut(sq_pos), FadeOut(lsp),
            FadeOut(sq_neg), FadeOut(lsn),
            FadeOut(note_two),
            run_time=0.6,
        )
        self.remove(z_main, lz, sq_pos, lsp, sq_neg, lsn, note_two)
        self.wait(0.2)

        # ── Orbit ring ────────────────────────────────────────────────────
        orbit_ring = Circle(radius=1.8, color="#445566", stroke_width=1.6)
        self.add_fixed_in_frame_mobjects(orbit_ring)
        self.play(Create(orbit_ring), run_time=0.8)

        # ── Traces — build first, then animate Create ─────────────────────
        # DO NOT register with add_fixed_in_frame_mobjects before Create —
        # that causes a full-opacity flash before the stroke is drawn.
        z_trace = ParametricFunction(
            lambda t: np.array([1.8 * np.cos(t), 1.8 * np.sin(t), 0]),
            t_range=[0, 2 * PI], color=YELLOW, stroke_width=2.5,
        )
        sqrt_trace = ParametricFunction(
            lambda t: np.array([
                np.sqrt(1.8) * np.cos(t / 2),
                np.sqrt(1.8) * np.sin(t / 2), 0,
            ]),
            t_range=[0, 2 * PI], color="#00ffcc", stroke_width=3.5,
        )
        # Set invisible, register, then Create draws them stroke by stroke
        z_trace.set_opacity(0)
        sqrt_trace.set_opacity(0)
        self.add_fixed_in_frame_mobjects(z_trace, sqrt_trace)
        z_trace.set_opacity(1)
        sqrt_trace.set_opacity(1)
        self.play(Create(z_trace), Create(sqrt_trace), run_time=2.8)
        self.wait(0.5)

        # NOTE 2 — orbit explanation (plain Text — no VGroup, no glitch)
        # Register → FadeIn → wait → FadeOut → remove — all strict steps
        note_orbit = Text(
            "z orbits origin once  (yellow)  —  sqrt(z)  only covers half  (cyan)",
            font_size=NOTE_SIZE - 2, color="#9999bb",
            font=NOTE_FONT, stroke_width=NOTE_STROKE,
        )
        note_orbit.to_edge(DOWN, buff=0.45)
        self.add_fixed_in_frame_mobjects(note_orbit)
        self.play(FadeIn(note_orbit), run_time=0.5)
        self.wait(2.0)
        self.play(FadeOut(note_orbit), run_time=0.4)
        self.remove(note_orbit)
        self.wait(0.15)

        # NOTE 3 — jump explanation
        note_jump = Text(
            "After one full loop, sqrt(z) JUMPS — the flat plane can't handle this!",
            font_size=NOTE_SIZE, color="#ff4466", weight=BOLD,
            font=NOTE_FONT, stroke_width=NOTE_STROKE,
        )
        note_jump.to_edge(DOWN, buff=0.45)
        self.add_fixed_in_frame_mobjects(note_jump)
        self.play(FadeIn(note_jump), run_time=0.5)
        self.wait(2.4)
        self.play(FadeOut(note_jump), run_time=0.4)
        self.remove(note_jump)
        self.wait(0.15)

        # NOTE 4 — Riemann's fix
        note_fix = Text(
            "Riemann's idea:  stack multiple copies of the plane, one per value",
            font_size=NOTE_SIZE, color="#00e5ff", weight=BOLD,
            font=NOTE_FONT, stroke_width=NOTE_STROKE,
        )
        note_fix.to_edge(DOWN, buff=0.45)
        self.add_fixed_in_frame_mobjects(note_fix)
        self.play(FadeIn(note_fix, shift=UP * 0.1), run_time=0.6)
        self.wait(3.0)
        self.play(FadeOut(note_fix), run_time=0.4)
        self.remove(note_fix)

        # ── Fade out everything in Part 2 cleanly ────────────────────────
        self.play(
            FadeOut(plane2),
            FadeOut(orbit_ring),
            FadeOut(z_trace),
            FadeOut(sqrt_trace),
            FadeOut(lbl2),
            run_time=0.8,
        )
        self.remove(plane2, orbit_ring, z_trace, sqrt_trace, lbl2)

        # ══════════════════════════════════════════════════════════════════
        # PART 3 — RIEMANN SURFACE FOR √z  (2 sheets)
        # ══════════════════════════════════════════════════════════════════
        self.set_camera_orientation(phi=78 * DEGREES, theta=-25 * DEGREES)

        lbl3_pre  = Text("Step 3  —  Riemann Surface for  ",
                         font_size=24, color="#00ffcc", weight=BOLD,
                         font=NOTE_FONT, stroke_width=HDR_STROKE)
        lbl3_sqrt = MathTex(r"\sqrt{z}", font_size=36, color="#00ffcc")
        lbl3_post = Text("   (2 sheets)",
                         font_size=24, color="#00ffcc", weight=BOLD,
                         font=NOTE_FONT, stroke_width=HDR_STROKE)
        lbl3 = VGroup(lbl3_pre, lbl3_sqrt, lbl3_post).arrange(RIGHT, buff=0.08)
        lbl3.to_edge(UP, buff=0.55)
        self.add_fixed_in_frame_mobjects(lbl3)
        self.play(FadeIn(lbl3), run_time=0.5)

        sheet1 = Surface(
            lambda u, v: np.array([u * np.cos(v), u * np.sin(v), v / (2 * PI) - 1.0]),
            u_range=[0.18, 2.3], v_range=[0, 4 * PI],
            resolution=(18, 64), fill_opacity=0.55,
            checkerboard_colors=["#082838", "#0c3a50"],
        )
        sheet1.set_color_by_gradient(TEAL_D, BLUE_C, TEAL_C, "#00ffcc")
        branch = Sphere(radius=0.09, color="#ff4444")
        branch.move_to(ORIGIN)

        self.play(Create(sheet1, run_time=3.2), FadeIn(branch, scale=2.5, run_time=1.5))

        note3_a = Text(
            "Same  (x, y)  point — two different heights = two sheets",
            font_size=NOTE_SIZE, color=NOTE_COLOR,
            font=NOTE_FONT, stroke_width=NOTE_STROKE,
        )
        note3_a.to_edge(DOWN, buff=0.5)
        self.add_fixed_in_frame_mobjects(note3_a)
        self.play(FadeIn(note3_a), run_time=0.5)

        self.move_camera(phi=88 * DEGREES, theta=-25 * DEGREES, zoom=1.3, run_time=2.2, rate_func=smooth)
        self.wait(1.2)
        self.move_camera(phi=88 * DEGREES, theta=155 * DEGREES, zoom=1.3, run_time=3.2, rate_func=smooth)
        self.move_camera(phi=32 * DEGREES, theta=240 * DEGREES, zoom=1.0, run_time=2.2, rate_func=smooth)

        s1_lbl = Text("Sheet 1  (+ branch)", font_size=19, color="#00ffcc",
                      font=NOTE_FONT, stroke_width=NOTE_STROKE)
        s1_lbl.to_corner(DL, buff=0.5)
        s2_lbl = Text("Sheet 2  (− branch)", font_size=19, color="#ff9944",
                      font=NOTE_FONT, stroke_width=NOTE_STROKE)
        s2_lbl.to_corner(DR, buff=0.5)
        self.add_fixed_in_frame_mobjects(s1_lbl, s2_lbl)
        self.play(FadeIn(s1_lbl), FadeIn(s2_lbl), run_time=0.5)

        traveler = Dot3D(point=np.array([1.6, 0.0, -1.0]), radius=0.09, color=YELLOW)
        glow     = Dot3D(point=np.array([1.6, 0.0, -1.0]), radius=0.16, color=YELLOW, fill_opacity=0.25)
        travel_path = ParametricFunction(
            lambda t: np.array([1.6 * np.cos(t), 1.6 * np.sin(t), t / (2 * PI) - 1.0]),
            t_range=[0, 4 * PI], color=YELLOW, stroke_width=3,
        )

        note3_b = Text(
            "Traveler spirals smoothly — both values visited,  no jump!",
            font_size=NOTE_SIZE, color="#ffdd00",
            font=NOTE_FONT, stroke_width=NOTE_STROKE,
        )
        note3_b.to_edge(DOWN, buff=0.5)
        self.add_fixed_in_frame_mobjects(note3_b)
        self.play(FadeOut(note3_a), FadeIn(note3_b), run_time=0.4)
        self.remove(note3_a)
        self.play(FadeIn(traveler, scale=2.5), FadeIn(glow, scale=2.5), run_time=0.4)
        self.play(
            MoveAlongPath(traveler, travel_path),
            MoveAlongPath(glow, travel_path.copy()),
            run_time=5.5, rate_func=linear,
        )
        self.play(FadeOut(traveler, scale=0.3), FadeOut(glow, scale=0.3), run_time=0.3)

        self.move_camera(phi=50 * DEGREES, theta=420 * DEGREES, zoom=0.92, run_time=3.0, rate_func=smooth)
        self.begin_ambient_camera_rotation(rate=0.13)
        self.wait(3.0)
        self.stop_ambient_camera_rotation()

        self.play(*[FadeOut(m) for m in [sheet1, branch, lbl3, note3_b, s1_lbl, s2_lbl]], run_time=0.8)
        self.remove(lbl3, note3_b, s1_lbl, s2_lbl)

        # ══════════════════════════════════════════════════════════════════
        # PART 4 — RIEMANN SURFACE FOR log(z)  (infinite sheets — helicoid)
        # ══════════════════════════════════════════════════════════════════
        self.set_camera_orientation(phi=68 * DEGREES, theta=-15 * DEGREES)

        lbl4 = Text("Step 4  —  log(z):  infinitely many sheets",
                    font_size=24, color="#ff9944", weight=BOLD,
                    font=NOTE_FONT, stroke_width=HDR_STROKE)
        lbl4.to_edge(UP, buff=0.55)
        self.add_fixed_in_frame_mobjects(lbl4)
        self.play(FadeIn(lbl4), run_time=0.5)

        helicoid = Surface(
            lambda u, v: np.array([u * np.cos(v), u * np.sin(v), v / (2 * PI)]),
            u_range=[0.22, 2.1], v_range=[-4 * PI, 4 * PI],
            resolution=(16, 84), fill_opacity=0.52,
            checkerboard_colors=["#1a082a", "#280d40"],
        )
        helicoid.set_color_by_gradient("#9933cc", "#ff4488", ORANGE, YELLOW_C, TEAL_C, "#9933cc")

        axis_pole = Line3D(np.array([0, 0, -2.2]), np.array([0, 0, 2.2]),
                           color="#333355", thickness=0.012)
        level_rings = VGroup(*[
            ParametricFunction(
                lambda t, h=h: np.array([1.98 * np.cos(t), 1.98 * np.sin(t), h]),
                t_range=[0, TAU], color="#334455", stroke_width=1.2, stroke_opacity=0.5,
            )
            for h in [-2, -1, 0, 1, 2]
        ])

        self.play(Create(helicoid, run_time=3.5), Create(axis_pole, run_time=1.5),
                  Create(level_rings, run_time=2.0))

        note4_a = Text(
            "Each floor  =  one complete orbit of  z  around the origin",
            font_size=NOTE_SIZE, color=NOTE_COLOR,
            font=NOTE_FONT, stroke_width=NOTE_STROKE,
        )
        note4_a.to_edge(DOWN, buff=0.5)
        self.add_fixed_in_frame_mobjects(note4_a)
        self.play(FadeIn(note4_a), run_time=0.5)

        self.move_camera(phi=82 * DEGREES, theta=-15 * DEGREES, zoom=1.0, run_time=1.5, rate_func=smooth)
        self.move_camera(phi=72 * DEGREES, theta=180 * DEGREES, zoom=0.88, run_time=3.5, rate_func=smooth)
        self.move_camera(phi=52 * DEGREES, theta=360 * DEGREES, zoom=0.80, run_time=3.0, rate_func=smooth)
        self.move_camera(phi=75 * DEGREES, theta=520 * DEGREES, zoom=0.88, run_time=3.0, rate_func=smooth)

        note4_b = Text(
            "This infinite staircase IS the Riemann surface for  log(z)",
            font_size=NOTE_SIZE, color="#ff9944", weight=BOLD,
            font=NOTE_FONT, stroke_width=NOTE_STROKE,
        )
        note4_b.to_edge(DOWN, buff=0.5)
        self.add_fixed_in_frame_mobjects(note4_b)
        self.play(FadeOut(note4_a), FadeIn(note4_b), run_time=0.6)
        self.remove(note4_a)

        h_traveler = Dot3D(point=np.array([1.5, 0.0, -2.0]), radius=0.09, color=WHITE)
        h_path = ParametricFunction(
            lambda t: np.array([1.5 * np.cos(t), 1.5 * np.sin(t), t / (2 * PI)]),
            t_range=[-4 * PI, 4 * PI], color=WHITE, stroke_width=3,
        )
        self.play(FadeIn(h_traveler, scale=2.5), run_time=0.3)
        self.play(MoveAlongPath(h_traveler, h_path), run_time=5.0, rate_func=linear)
        self.play(FadeOut(h_traveler, scale=0.3), run_time=0.3)

        self.begin_ambient_camera_rotation(rate=0.12)
        self.wait(3.5)
        self.stop_ambient_camera_rotation()

        self.play(*[FadeOut(m) for m in [helicoid, axis_pole, level_rings, lbl4, note4_b]], run_time=0.8)
        self.remove(lbl4, note4_b)

        # ══════════════════════════════════════════════════════════════════
        # PART 5 — CLOSING SUMMARY CARD
        # ══════════════════════════════════════════════════════════════════
        self.set_camera_orientation(phi=0, theta=-PI / 2)

        heading = Text("What is a Riemann Surface?",
                       font_size=36, color="#00e5ff", weight=BOLD,
                       font=NOTE_FONT, stroke_width=HDR_STROKE)
        heading.to_corner(UL, buff=0.5)

        line1 = Text("A complex function can produce multiple outputs for one input.",
                     font_size=19, color=NOTE_COLOR, font=NOTE_FONT, stroke_width=NOTE_STROKE)
        line2 = Text("On a flat plane this causes unavoidable discontinuous jumps.",
                     font_size=19, color=NOTE_COLOR, font=NOTE_FONT, stroke_width=NOTE_STROKE)
        line3 = Text("A Riemann surface stacks extra sheets so every value",
                     font_size=19, color=NOTE_COLOR, font=NOTE_FONT, stroke_width=NOTE_STROKE)
        line4 = Text("gets its own smooth home — no jumping, no ambiguity.",
                     font_size=19, color=NOTE_COLOR, font=NOTE_FONT, stroke_width=NOTE_STROKE)

        divider = Line(LEFT * 0.1, RIGHT * 5.8, color="#222244", stroke_width=1)

        ex1_math = MathTex(r"\sqrt{z}", font_size=28, color="#00ffcc")
        ex1_post = Text("  →  2 sheets joined at  z = 0  (branch point)",
                        font_size=19, color="#00ffcc", font=NOTE_FONT, stroke_width=NOTE_STROKE)
        ex1 = VGroup(ex1_math, ex1_post).arrange(RIGHT, buff=0.10)

        ex2 = Text("log(z)  →  infinitely many sheets, winding upward forever",
                   font_size=19, color="#ff9944", font=NOTE_FONT, stroke_width=NOTE_STROKE)

        punchline = Text(
            "Riemann surfaces turn multi-valued functions into single-valued ones.",
            font_size=19, color="#ffdd00", weight=BOLD,
            font=NOTE_FONT, stroke_width=NOTE_STROKE,
        )

        # Stack all lines left-aligned, then anchor the whole block to the left edge
        body = VGroup(line1, line2, line3, line4, divider, ex1, ex2, punchline)
        body.arrange(DOWN, buff=0.30, aligned_edge=LEFT)
        body.next_to(heading, DOWN, buff=0.40)
        body.align_to(heading, LEFT)

        self.add_fixed_in_frame_mobjects(heading)
        self.play(FadeIn(heading, shift=DOWN * 0.2), run_time=0.9)

        for mob in body:
            self.add_fixed_in_frame_mobjects(mob)
            self.play(FadeIn(mob, shift=RIGHT * 0.12), run_time=0.42)

        self.wait(6.0)
        self.play(FadeOut(heading), *[FadeOut(m) for m in body], run_time=1.2)

# Commented out IPython magic to ensure Python compatibility.
# %%manim -ql RiemannSurfaces