# -*- coding: utf-8 -*-
"""DFSVisualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7m6C6SuiMNscQkH_2KEW88kzt3M_n1p
"""

!sudo apt update
!sudo apt install -y ffmpeg libcairo2-dev libpango1.0-dev texlive texlive-latex-extra texlive-fonts-recommended texlive-xetex

!pip install manim
print("✅ Installation complete!")

"""
DFS Algorithm Visualization
Run with:  manim -pql dfs_visualization.py DFSVisualization
"""

from manim import *

# Palette
C_BG      = "#0A0E1A"
C_NODE    = "#1A73E8"
C_VISIT   = "#1E8C45"
C_ACTIVE  = "#F4A61D"
C_EDGE    = "#2E3D55"
C_EVIS    = "#56CCB2"
C_WHITE   = "#F0F4FF"
C_DIM     = "#5A6A80"
C_GOLD    = "#FFD166"
C_CARD    = "#111827"


class DFSVisualization(Scene):

    def construct(self):
        self.camera.background_color = C_BG
        self._part1_intro()
        self._part2_traversal()
        self._part3_cards()

    # ─────────────────────────────────────────────────────────
    def _node(self, label, color=C_NODE):
        ring = Circle(radius=0.42, fill_color=color, fill_opacity=1,
                      stroke_color=C_WHITE, stroke_width=2.5)
        lbl  = Text(label, font_size=26, color=C_WHITE, weight=BOLD)
        return VGroup(ring, lbl)

    def _edge(self, a, b, color=C_EDGE):
        return Line(a.get_center(), b.get_center(),
                    stroke_width=2.5, color=color, buff=0.42)

    def _wipe(self):
        self.play(FadeOut(Group(*self.mobjects)), run_time=0.45)

    # =========================================================
    #  PART 1  ·  Intro slide
    # =========================================================
    def _part1_intro(self):
        title = Text("Depth-First Search",
                     font_size=68, color=C_GOLD, weight=BOLD)
        title.move_to(UP * 2.4)
        self.play(DrawBorderThenFill(title), run_time=1.1)

        defn = Text(
            "Start at a node. Go as deep as you can.\n"
            "Hit a dead end? Back up and try the next path.",
            font_size=27, color=C_WHITE, line_spacing=1.5,
        )
        defn.next_to(title, DOWN, buff=0.5)
        self.play(FadeIn(defn, shift=UP * 0.2), run_time=0.8)
        self.wait(0.6)

        pill_data = [
            ("1", "Go DEEP before going wide",    "#1A73E8"),
            ("2", "Use a Stack to track the path", "#7B2FBE"),
            ("3", "Never revisit a visited node",  "#1E8C45"),
        ]
        pills = VGroup()
        for num, txt, col in pill_data:
            bubble = RoundedRectangle(
                width=6.2, height=0.72, corner_radius=0.36,
                fill_color=col, fill_opacity=0.18,
                stroke_color=col, stroke_width=1.8,
            )
            num_t = Text(num, font_size=22, color=col, weight=BOLD)
            txt_t = Text(txt, font_size=22, color=C_WHITE)
            row   = VGroup(num_t, txt_t).arrange(RIGHT, buff=0.4)
            row.move_to(bubble)
            pills.add(VGroup(bubble, row))

        pills.arrange(DOWN, buff=0.28).next_to(defn, DOWN, buff=0.55)

        for pill in pills:
            self.play(FadeIn(pill, shift=RIGHT * 0.35), run_time=0.45)
        self.wait(2)
        self._wipe()

    # =========================================================
    #  PART 2  ·  Live graph traversal
    # =========================================================
    def _part2_traversal(self):
        hdr = Text("Watch DFS Traverse a Graph",
                   font_size=34, color=C_GOLD, weight=BOLD)
        hdr.to_edge(UP, buff=0.32)
        self.play(Write(hdr))

        # ── Graph layout ──────────────────────────────────────
        POS = {
            "A": LEFT  * 4.5 + UP * 0.5,
            "B": LEFT  * 2.0 + UP * 2.0,
            "C": LEFT  * 2.0 + DOWN * 1.0,
            "D": ORIGIN + UP * 2.8,
            "E": ORIGIN + DOWN * 0.4,
            "F": RIGHT * 2.8 + UP * 2.0,
            "G": RIGHT * 2.8 + UP * 0.5,
        }

        # ── Adjacency — every edge explained ──────────────────
        #
        #  A──B   A's first neighbour. DFS dives to B immediately.
        #  A──C   A's second neighbour. Only visited after B's full subtree.
        #  B──D   B's first unvisited. DFS continues deeper via D.
        #  B──F   B's second unvisited. Visited after D's entire branch.
        #  D──G   D's only unvisited. One more level deeper.
        #  G──E   G's ONLY unvisited. G is NOT a dead end — must go to E.
        #  E──C   E's only unvisited. One final forward step.
        #
        #  Correct DFS visit order: A → B → D → G → E → C → F
        #
        #  Dead ends in order:
        #    C: neighbours A(visited) + E(visited) → 1st dead end
        #    E: neighbours C(visited) + G(visited) → dead end on backtrack
        #    G: neighbours D(visited) + E(visited) → dead end on backtrack
        #    D: neighbours B(visited) + G(visited) → dead end on backtrack
        #    F: only neighbour B(visited)           → 2nd dead end
        ADJ = {
            "A": ["B", "C"],
            "B": ["A", "D", "F"],
            "C": ["A", "E"],
            "D": ["B", "G"],
            "E": ["C", "G"],
            "F": ["B"],
            "G": ["D", "E"],
        }

        nodes = {k: self._node(k).move_to(v) for k, v in POS.items()}

        edges, eg = {}, VGroup()
        for s, ns in ADJ.items():
            for d in ns:
                key = tuple(sorted([s, d]))
                if key not in edges:
                    e = self._edge(nodes[s], nodes[d])
                    edges[key] = e
                    eg.add(e)

        self.play(Create(eg), run_time=1.0)
        self.play(
            LaggedStart(*[FadeIn(n, scale=0.5) for n in nodes.values()],
                        lag_ratio=0.12),
            run_time=1.2,
        )
        self.wait(0.5)

        # ── Caption bar ───────────────────────────────────────
        cap_bg = Rectangle(
            width=14.2, height=1.3,
            fill_color="#03060F", fill_opacity=1,
            stroke_width=0,
        ).to_edge(DOWN, buff=0)
        self.play(FadeIn(cap_bg))

        def show_caption(msg, color=C_WHITE, old=None):
            new = Text(msg, font_size=23, color=color)
            new.to_edge(DOWN, buff=0.38)
            if old is not None:
                self.play(
                    FadeOut(old, shift=UP * 0.12),
                    FadeIn(new,  shift=UP * 0.12),
                    run_time=0.45,
                )
            else:
                self.play(FadeIn(new), run_time=0.45)
            return new

        def visit(lbl):
            nodes[lbl][0].set_fill(C_ACTIVE)
            self.play(nodes[lbl].animate.scale(1.32), run_time=0.28)
            self.play(nodes[lbl].animate.scale(1 / 1.32), run_time=0.22)
            nodes[lbl][0].set_fill(C_VISIT)

        def light_edge(a, b):
            key = tuple(sorted([a, b]))
            self.play(
                edges[key].animate.set_color(C_EVIS).set_stroke(width=4),
                run_time=0.35,
            )

        def dead_end(lbl):
            ring = Circle(radius=0.58, color="#E53935", stroke_width=5)
            ring.move_to(nodes[lbl].get_center())
            cross_h = Line(LEFT * 0.22, RIGHT * 0.22,
                           color="#E53935", stroke_width=4)
            cross_v = Line(UP * 0.22,   DOWN  * 0.22,
                           color="#E53935", stroke_width=4)
            cross_h.move_to(ring); cross_v.move_to(ring)
            marker = VGroup(ring, cross_h, cross_v)
            self.play(FadeIn(marker, scale=0.6), run_time=0.35)
            self.wait(1.4)
            self.play(FadeOut(marker), run_time=0.3)

        def backtrack(frm, to):
            arr = Arrow(
                nodes[frm].get_center(), nodes[to].get_center(),
                color="#F4A61D", stroke_width=5,
                buff=0.44, max_tip_length_to_length_ratio=0.18,
            )
            self.play(Create(arr), run_time=0.55)
            self.wait(0.6)
            self.play(FadeOut(arr), run_time=0.3)

        # ── START badge ───────────────────────────────────────
        start_badge = Text("START", font_size=16, color=C_GOLD, weight=BOLD)
        start_badge.next_to(nodes["A"], UP, buff=0.15)
        self.play(FadeIn(start_badge, shift=DOWN * 0.1))
        cap = show_caption("Start at A.  DFS always goes as deep as possible first.")
        self.wait(2.2)

        # ══ STEP 1 — visit A ══════════════════════════════════
        visit("A")
        cap = show_caption("A visited.  A connects to B and C.  Pick B first — go deeper.", old=cap)
        self.wait(2.0)
        light_edge("A", "B")

        # ══ STEP 2 — visit B ══════════════════════════════════
        # KEY POINT 1: B connects to D and F — not G.
        # G is D's neighbour. B reaches G only by going through D first.
        # KEY POINT 2: why D before F?
        # DFS always picks the first unvisited neighbour in order.
        # D comes before F in B's list — so D is chosen. F waits here at B.
        visit("B")
        cap = show_caption("B connects to D and F.  B does NOT connect to G.", old=cap)
        self.wait(2.2)
        cap = show_caption("G is D's neighbour — B reaches G only by going through D.", old=cap)
        self.wait(2.2)
        cap = show_caption("D comes before F in the list.  Go to D first.  F stays and waits at B.", old=cap)
        self.wait(2.5)
        light_edge("B", "D")

        # ══ STEP 3 — visit D ══════════════════════════════════
        # D connects to B (visited) and G. G is the only forward path.
        visit("D")
        cap = show_caption("D visited.  D connects to B (done) and G.  Only G is new — go there.", old=cap)
        self.wait(2.2)
        light_edge("D", "G")

        # ══ STEP 4 — visit G ══════════════════════════════════
        # G connects to D (visited) and E.
        # KEY POINT 3: E-G cross-connection.
        # E sits in the OTHER branch of the graph — hanging off C which hangs off A.
        # The G-E edge is a cross-connection joining the two sides of the graph.
        # Without it, G would be a dead end. Because of it, DFS crosses over to E.
        visit("G")
        cap = show_caption("G visited.  G connects to D (done) and E.", old=cap)
        self.wait(2.0)
        cap = show_caption("E is on the OTHER side of the graph — G-E is a cross-connection.", old=cap)
        self.wait(2.2)
        cap = show_caption("This edge joins the two halves.  DFS crosses over to E now.", old=cap)
        self.wait(2.5)
        light_edge("G", "E")

        # ══ STEP 5 — visit E ══════════════════════════════════
        # E connects to C (unvisited) and G (visited).
        # Because we crossed over via G-E, we now explore C from E's side —
        # C will never be reached from A directly.
        visit("E")
        cap = show_caption("E visited.  E connects to C (unvisited) and G (done).  Go to C.", old=cap)
        self.wait(2.2)
        light_edge("E", "C")

        # ══ STEP 6 — visit C  →  FIRST DEAD END ═══════════════
        # C connects to A (visited) and E (visited).
        # Note: C was reached from E, not from A directly.
        # The G-E cross-connection caused C to be visited from the right side.
        visit("C")
        cap = show_caption("C visited.  C connects to A (done) and E (done).  No new paths.", old=cap)
        self.wait(2.0)
        dead_end("C")
        cap = show_caption("Dead end at C.  C was reached via G-E, not via A.  Backtrack.", "#E53935", old=cap)
        self.wait(2.2)

        backtrack("C", "E")
        cap = show_caption("Back at E.  Both neighbours visited.  Keep backtracking.", C_ACTIVE, old=cap)
        self.wait(1.5)

        backtrack("E", "G")
        cap = show_caption("Back at G.  Both neighbours visited.  Keep backtracking.", C_ACTIVE, old=cap)
        self.wait(1.5)

        backtrack("G", "D")
        cap = show_caption("Back at D.  Both neighbours visited.  Keep backtracking.", C_ACTIVE, old=cap)
        self.wait(1.5)

        backtrack("D", "B")
        cap = show_caption("Back at B.  F was left waiting here — now it is B's turn to visit F.", C_ACTIVE, old=cap)
        self.wait(2.2)
        light_edge("B", "F")

        # ══ STEP 7 — visit F  →  SECOND DEAD END ══════════════
        # F connects only to B. B is already visited.
        # F has one edge and it leads back — dead end.
        visit("F")
        cap = show_caption("F visited.  F only connects to B (done).  Dead end.", old=cap)
        self.wait(2.0)
        dead_end("F")
        cap = show_caption("Dead end at F.  Backtrack to A.", "#E53935", old=cap)
        self.wait(2.0)

        backtrack("F", "B")
        cap = show_caption("Back at B.  All three neighbours visited.  Keep backtracking.", C_ACTIVE, old=cap)
        self.wait(1.5)

        backtrack("B", "A")
        cap = show_caption("Back at A.  C was already visited via the G-E cross-connection.  Done.", C_ACTIVE, old=cap)
        self.wait(2.2)

        # ══ DONE ══════════════════════════════════════════════
        cap = show_caption("All 7 nodes visited:  A  B  D  G  E  C  F.  DFS complete.", C_VISIT, old=cap)
        for n in nodes.values():
            self.play(Indicate(n, color=C_VISIT, scale_factor=1.18), run_time=0.25)
        self.wait(2.8)
        self._wipe()

    # =========================================================
    #  PART 3  ·  Four use-case cards — 2 rows x 2 cols
    # =========================================================
    def _part3_cards(self):
        SCENE_TOP    =  3.6
        SCENE_BOTTOM = -4.0
        SCENE_H      = SCENE_TOP - SCENE_BOTTOM

        HDR_H     = 0.6
        HDR_PAD   = 0.30
        TAG_H     = 0.35
        TAG_PAD   = 0.32
        GRID_PAD  = 0.28

        avail_h = (SCENE_H
                   - HDR_H - HDR_PAD
                   - TAG_H - TAG_PAD
                   - GRID_PAD * 2
                   - 0.30)

        ROW_GAP  = 0.28
        CARD_H   = (avail_h - ROW_GAP) / 2
        COL_GAP  = 0.24
        CARD_W   = (12.0 - COL_GAP) / 2

        hdr = Text("Where DFS Is Used", font_size=36, color=C_GOLD, weight=BOLD)
        hdr.move_to([0, SCENE_TOP - HDR_H / 2, 0])
        self.play(Write(hdr))

        closing = Text(
            "One rule — go deep first — powers more than you think.",
            font_size=21, color=C_GOLD, slant=ITALIC,
        )
        closing.move_to([0, SCENE_BOTTOM + TAG_PAD + TAG_H / 2, 0])

        DATA = [
            (
                "Web Crawlers", "#1A73E8",
                "Search engines dive deep into every\n"
                "link on a page before moving on —\n"
                "the same depth-first logic DFS uses.",
            ),
            (
                "Cycle Detection", "#7B2FBE",
                "Compilers use DFS to catch circular\n"
                "imports. A path that leads back to a\n"
                "visited node means a cycle exists.",
            ),
            (
                "Topological Sort", "#0D7C5F",
                "Build tools run DFS to order tasks.\n"
                "Each dependency is fully resolved\n"
                "before the code that needs it runs.",
            ),
            (
                "Game AI", "#C0392B",
                "Chess engines go as deep as possible\n"
                "down each move sequence, then\n"
                "backtrack — exactly like DFS.",
            ),
        ]

        def build_card(title, accent, body):
            bg = RoundedRectangle(
                width=CARD_W, height=CARD_H, corner_radius=0.18,
                fill_color="#0D1220", fill_opacity=1,
                stroke_color=accent, stroke_width=1.8,
            )
            bg.move_to(ORIGIN)
            stripe = Rectangle(
                width=0.16, height=CARD_H,
                fill_color=accent, fill_opacity=1, stroke_width=0,
            )
            stripe.move_to(bg.get_left() + RIGHT * 0.08)
            INSET = 0.42
            t = Text(title, font_size=22, color=C_WHITE, weight=BOLD)
            t.move_to(bg.get_corner(UL) + RIGHT * (INSET + t.width / 2)
                                        + DOWN  * 0.36)
            t.align_to(bg.get_left() + RIGHT * INSET, LEFT)
            rule = Line(
                bg.get_left()  + RIGHT * (INSET - 0.04),
                bg.get_right() + LEFT  * 0.14,
                color=accent, stroke_width=0.8, stroke_opacity=0.45,
            )
            rule.next_to(t, DOWN, buff=0.13)
            b = Text(body, font_size=18, color=C_WHITE, line_spacing=1.3)
            b.next_to(rule, DOWN, buff=0.18)
            b.align_to(bg.get_left() + RIGHT * INSET, LEFT)
            return VGroup(bg, stripe, t, rule, b)

        cards = [build_card(*d) for d in DATA]
        c1, c2, c3, c4 = cards

        row1 = VGroup(c1, c2).arrange(RIGHT, buff=COL_GAP)
        row2 = VGroup(c3, c4).arrange(RIGHT, buff=COL_GAP)
        grid = VGroup(row1, row2).arrange(DOWN, buff=ROW_GAP)

        grid_center_y = (
            (hdr.get_bottom()[1] - HDR_PAD)
            + (closing.get_top()[1] + GRID_PAD)
        ) / 2
        grid.move_to([0, grid_center_y, 0])

        row1.shift(LEFT * 14)
        row2.shift(RIGHT * 14)

        self.play(row1.animate.shift(RIGHT * 14), run_time=0.65)
        self.wait(0.15)
        self.play(row2.animate.shift(LEFT * 14), run_time=0.65)
        self.wait(1.8)

        self.play(Write(closing))
        self.wait(3.5)

# Commented out IPython magic to ensure Python compatibility.
# %%manim -ql DFSVisualization