# -*- coding: utf-8 -*-
"""FibonacciGolden.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yWWsGq7A9K8o_Wy755-KAhKH9GKfb9YE
"""

!sudo apt update
!sudo apt install -y ffmpeg libcairo2-dev libpango1.0-dev texlive texlive-latex-extra texlive-fonts-recommended texlive-xetex

!pip install manim
print("✅ Installation complete!")

"""
Fibonacci Spiral & The Golden Ratio
=====================================
Local preview:
    manim -pql fibonacci_golden.py FibonacciGolden --disable_caching

High quality:
    manim -pqh fibonacci_golden.py FibonacciGolden --disable_caching

Colab:
    !manim -pqh fibonacci_golden.py FibonacciGolden --disable_caching
"""

from manim import *
import numpy as np

# ── Palette ─────────────────────────────────────────────────────────────────
BG       = "#05050f"
C_GOLD   = ManimColor("#ffdd00")
C_CYAN   = ManimColor("#00e5ff")
C_GREEN  = ManimColor("#44ff99")
C_ORANGE = ManimColor("#ff9944")
C_RED    = ManimColor("#ff3344")
C_PURPLE = ManimColor("#cc44ff")
C_PINK   = ManimColor("#ff4488")
C_WHITE  = ManimColor("#e8e8f0")
C_DIM    = ManimColor("#aaaacc")
PHI      = (1 + np.sqrt(5)) / 2   # 1.6180339…

RNG = np.random.default_rng(7)


class FibonacciGolden(ThreeDScene):
    def construct(self):
        self.camera.background_color = ManimColor(BG)
        self.part0_title()
        self.part1_sequence()
        self.part2_rectangles()
        self.part3_spiral_2d()
        self.part4_golden_ratio()
        self.part5_spiral_3d()
        self.part6_math()
        self.part7_nature()

    # ══════════════════════════════════════════════════════════════════════
    # PART 0 — CINEMATIC TITLE
    # ══════════════════════════════════════════════════════════════════════
    def part0_title(self):
        self.set_camera_orientation(phi=0, theta=-PI / 2)

        t1  = Text("Fibonacci Spiral",   font_size=64, color=C_GOLD,  weight=BOLD)
        amp = Text("&",                  font_size=40, color=C_WHITE)
        t2  = Text("The Golden Ratio",   font_size=64, color=C_CYAN,  weight=BOLD)
        sub = Text("φ = 1.6180339…  —  nature's hidden blueprint",
                   font_size=24, color=C_DIM)
        grp = VGroup(t1, amp, t2, sub).arrange(DOWN, buff=0.35)

        # golden spiral ghost particles
        pal = [C_GOLD, C_CYAN, C_GREEN, C_ORANGE, C_PURPLE]
        dots = VGroup(*[
            Dot(
                point=[float(RNG.uniform(-6.8, 6.8)),
                        float(RNG.uniform(-3.9, 3.9)), 0],
                radius=float(RNG.uniform(0.025, 0.065)),
                color=pal[int(RNG.integers(0, len(pal)))],
            ).set_opacity(float(RNG.uniform(0.15, 0.80)))
            for _ in range(60)
        ])

        self.play(LaggedStartMap(FadeIn, dots, lag_ratio=0.025, run_time=1.1))
        self.play(Write(t1), run_time=1.0)
        self.play(FadeIn(amp), Write(t2), run_time=1.0)
        self.play(FadeIn(sub, shift=UP * 0.25))
        self.wait(2.0)
        self.play(FadeOut(VGroup(grp, dots)))

    # ══════════════════════════════════════════════════════════════════════
    # PART 1 — THE FIBONACCI SEQUENCE
    # ══════════════════════════════════════════════════════════════════════
    def part1_sequence(self):
        self.set_camera_orientation(phi=0, theta=-PI / 2)

        hdr = Text("STEP 1 — The Fibonacci Sequence",
                   font_size=30, color=C_CYAN, weight=BOLD).to_corner(UL)
        rule = Text("Each number = sum of the previous two",
                    font_size=22, color=C_DIM)
        rule.next_to(hdr, DOWN, aligned_edge=LEFT, buff=0.15)

        self.play(FadeIn(hdr), FadeIn(rule))

        fib = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
        colors_cycle = [C_GOLD, C_CYAN, C_GREEN, C_ORANGE,
                        C_PURPLE, C_PINK, C_RED, C_GOLD, C_CYAN, C_GREEN]

        boxes = VGroup()
        for i, (n, col) in enumerate(zip(fib, colors_cycle)):
            lbl = Text(str(n), font_size=28, color=col, weight=BOLD)
            bg  = RoundedRectangle(
                corner_radius=0.14,
                width=max(lbl.width + 0.38, 0.72),
                height=0.62,
                fill_color=col, fill_opacity=0.12,
                stroke_color=col, stroke_width=1.6,
            )
            bg.move_to(lbl)
            boxes.add(VGroup(bg, lbl))

        boxes.arrange(RIGHT, buff=0.22).center().shift(UP * 0.5)

        plus_signs = VGroup()
        for i in range(len(fib) - 1):
            ps = Text("+", font_size=20, color=C_DIM)
            ps.move_to((boxes[i].get_right() + boxes[i + 1].get_left()) / 2)
            plus_signs.add(ps)

        # Reveal boxes one at a time
        for i, box in enumerate(boxes):
            self.play(FadeIn(box, scale=0.7), run_time=0.28)
            if i < len(plus_signs):
                self.add(plus_signs[i])

        self.wait(0.6)

        # Highlight the addition rule: 5 + 8 = 13
        idx = 4   # fib[4]=5, fib[5]=8, fib[6]=13
        brace_grp = VGroup(boxes[idx], boxes[idx + 1])
        brace = Brace(brace_grp, DOWN, color=C_GOLD)
        eq_lbl = Text("5 + 8 = 13", font_size=26, color=C_GOLD)
        eq_lbl.next_to(brace, DOWN, buff=0.15)

        self.play(GrowFromCenter(brace), Write(eq_lbl), run_time=0.8)
        arr = Arrow(
            eq_lbl.get_right() + RIGHT * 0.1,
            boxes[idx + 2].get_bottom() + DOWN * 0.05,
            color=C_GOLD, buff=0.05, stroke_width=2.5,
        )
        self.play(GrowArrow(arr), run_time=0.5)
        self.wait(1.4)

        # Ratio convergence
        ratio_lbl = Text("Consecutive ratios  →  φ",
                         font_size=24, color=C_GREEN).to_edge(DOWN, buff=0.55)
        ratios = VGroup()
        for i in range(1, len(fib)):
            r = fib[i] / fib[i - 1]
            t = Text(f"{r:.4f}", font_size=18,
                     color=interpolate_color(C_ORANGE, C_GREEN,
                                             float(i / (len(fib) - 1))))
            ratios.add(t)
        ratios.arrange(RIGHT, buff=0.28)
        ratios.next_to(ratio_lbl, UP, buff=0.25)

        self.play(Write(ratio_lbl))
        self.play(LaggedStartMap(FadeIn, ratios, lag_ratio=0.12, run_time=1.4))
        self.wait(1.6)

        self.play(FadeOut(VGroup(hdr, rule, boxes, plus_signs,
                                 brace, eq_lbl, arr, ratio_lbl, ratios)))

    # ══════════════════════════════════════════════════════════════════════
    # PART 2 — FIBONACCI RECTANGLES TILING
    # ══════════════════════════════════════════════════════════════════════
    def part2_rectangles(self):
        self.set_camera_orientation(phi=0, theta=-PI / 2)

        hdr = Text("STEP 2 — Tiling with Squares",
                   font_size=30, color=C_CYAN, weight=BOLD).to_corner(UL)
        self.play(FadeIn(hdr))

        # Build Fibonacci squares laid out in the classic spiral tiling pattern.
        # Each square placed adjacent to the growing rectangle.
        # Sizes: 1,1,2,3,5,8  (scaled by S)
        S    = 0.55   # world-unit scale per Fibonacci unit
        cols = [C_CYAN, C_GOLD, C_GREEN, C_ORANGE, C_PURPLE, C_PINK]
        sizes = [1, 1, 2, 3, 5, 8]

        # Positions (bottom-left corner) for each square in Fibonacci tiling
        # Direction cycle: right, up, left, down
        positions = []
        bx, by = 0.0, 0.0   # current anchor (bottom-left of next square)
        # pre-computed for sizes [1,1,2,3,5,8]
        placements = [
            (0,  0,  'r'),
            (1,  0,  'u'),
            (-2, 1,  'l'),
            (-2, -3, 'd'),
            (3,  -3, 'r'),  # actually place right of full rect
            (3,  2,  'u'),
        ]

        # Recompute properly
        # start: square 0 at (0,0), size=1
        # square 1 placed right: (1,0)
        # square 2 (size 2) placed above both: (-0,1)? Let's just hardcode offsets
        # Classic arrangement (all in Fibonacci units, scaled by S, centered):
        raw = [
            (0,   0,  1),
            (1,   0,  1),
            (-1,  0,  2),   # left of sq0+sq1
            (-1, -3,  3),   # below the strip
            (2,  -3,  5),   # right
            (2,   2,  8),   # above
        ]
        # center the whole block
        total_w = 10 * S
        total_h = 10 * S
        ox = -total_w / 2
        oy = -total_h / 2 + 0.3

        squares = VGroup()
        for (rx, ry, sz), col in zip(raw, cols):
            sq = Square(side_length=sz * S, color=col,
                        fill_color=col, fill_opacity=0.13,
                        stroke_width=2.0)
            sq.move_to([ox + (rx + sz / 2) * S,
                        oy + (ry + sz / 2) * S, 0])
            num = Text(str(sz), font_size=int(14 + sz * 3),
                       color=col, weight=BOLD)
            num.move_to(sq.get_center())
            squares.add(VGroup(sq, num))

        for i, sq_grp in enumerate(squares):
            self.play(
                DrawBorderThenFill(sq_grp[0]),
                Write(sq_grp[1]),
                run_time=0.45,
            )

        note = Text("Every square's side = a Fibonacci number",
                    font_size=22, color=C_GOLD).to_edge(DOWN, buff=0.5)
        self.play(Write(note))
        self.wait(2.0)
        self.play(FadeOut(VGroup(hdr, squares, note)))

    # ══════════════════════════════════════════════════════════════════════
    # PART 3 — DRAWING THE SPIRAL
    # ══════════════════════════════════════════════════════════════════════
    def part3_spiral_2d(self):
        self.set_camera_orientation(phi=0, theta=-PI / 2)

        hdr = Text("STEP 3 — The Fibonacci Spiral",
                   font_size=30, color=C_CYAN, weight=BOLD).to_corner(UL)
        self.play(FadeIn(hdr))

        S  = 0.55
        ox = -5 * S
        oy = -5 * S + 0.3

        raw = [
            (0,   0,  1),
            (1,   0,  1),
            (-1,  0,  2),
            (-1, -3,  3),
            (2,  -3,  5),
            (2,   2,  8),
        ]
        cols = [C_CYAN, C_GOLD, C_GREEN, C_ORANGE, C_PURPLE, C_PINK]

        # Draw faded background squares
        squares = VGroup()
        for (rx, ry, sz), col in zip(raw, cols):
            sq = Square(side_length=sz * S, color=col,
                        fill_color=col, fill_opacity=0.07, stroke_width=1.2)
            sq.move_to([ox + (rx + sz / 2) * S,
                        oy + (ry + sz / 2) * S, 0])
            squares.add(sq)
        self.play(LaggedStartMap(FadeIn, squares, lag_ratio=0.1, run_time=0.9))

        # Quarter-circle arcs through each square corner
        # Centers and radii in scene coordinates
        arc_data = [
            # (cx, cy, radius, start_angle, arc_len)
            (ox + 1*S,   oy + 1*S,   1*S,  PI,       PI/2),
            (ox + 1*S,   oy + 0*S,   1*S,  PI/2,     PI/2),
            (ox + 1*S,   oy + 2*S,   2*S, -PI/2,     PI/2),
            (ox + 2*S,   oy + 0*S,   3*S,  PI,       PI/2),
            (ox + 7*S,   oy + 2*S,   5*S,  PI/2,     PI/2),
            (ox + 2*S,   oy + 10*S,  8*S,  0,        PI/2),
        ]

        arcs = VGroup()
        for (cx, cy, r, sa, al), col in zip(arc_data, cols):
            arc = Arc(
                radius=r, start_angle=sa, angle=al,
                arc_center=[cx, cy, 0],
                color=col, stroke_width=3.5,
            )
            arcs.add(arc)

        spiral_note = Text("Quarter-circle arcs through Fibonacci squares",
                           font_size=21, color=C_DIM).to_edge(DOWN, buff=0.5)
        self.play(Write(spiral_note))

        for arc in arcs:
            self.play(Create(arc), run_time=0.50)

        self.wait(1.6)
        self.play(FadeOut(VGroup(hdr, squares, arcs, spiral_note)))

    # ══════════════════════════════════════════════════════════════════════
    # PART 4 — THE GOLDEN RATIO REVEALED
    # ══════════════════════════════════════════════════════════════════════
    def part4_golden_ratio(self):
        self.set_camera_orientation(phi=0, theta=-PI / 2)

        hdr = Text("STEP 4 — The Golden Ratio  φ",
                   font_size=30, color=C_GOLD, weight=BOLD).to_corner(UL)
        self.play(FadeIn(hdr))

        # ── Golden rectangle — left half of screen ──────────────────────
        W, H = PHI * 2.0, 1 * 2.0
        rect = Rectangle(width=W, height=H,
                         color=C_GOLD, fill_color=C_GOLD,
                         fill_opacity=0.10, stroke_width=2.2)
        rect.move_to(LEFT * 2.8 + UP * 0.6)

        sq_side = H
        sq = Square(side_length=sq_side,
                    color=C_CYAN, fill_color=C_CYAN,
                    fill_opacity=0.14, stroke_width=2.0)
        sq.align_to(rect, LEFT)
        sq.align_to(rect, UP)

        self.play(DrawBorderThenFill(rect), run_time=0.8)
        self.play(DrawBorderThenFill(sq),  run_time=0.6)

        # ── Measurement arrows sit BELOW the rectangle with clear space ──
        arrow_y = rect.get_bottom()[1] - 0.45
        a_start = np.array([rect.get_left()[0],  arrow_y, 0])
        a_end   = np.array([sq.get_right()[0],   arrow_y, 0])
        b_start = np.array([sq.get_right()[0],   arrow_y, 0])
        b_end   = np.array([rect.get_right()[0], arrow_y, 0])

        a_arrow = DoubleArrow(a_start, a_end, color=C_CYAN,
                              buff=0, stroke_width=2.2)
        b_arrow = DoubleArrow(b_start, b_end, color=C_ORANGE,
                              buff=0, stroke_width=2.2)

        a_lbl = Text("a", font_size=22, color=C_CYAN,   weight=BOLD)
        b_lbl = Text("b", font_size=22, color=C_ORANGE, weight=BOLD)
        a_lbl.next_to(a_arrow, DOWN, buff=0.14)
        b_lbl.next_to(b_arrow, DOWN, buff=0.14)

        self.play(
            GrowFromCenter(a_arrow), Write(a_lbl),
            GrowFromCenter(b_arrow), Write(b_lbl),
            run_time=0.7,
        )

        # ── Right panel — equations stacked vertically ───────────────────
        # phi_lbl and exact sit in the right half, well away from arrows
        phi_lbl = MathTex(
            r"\varphi = \frac{a+b}{a} = \frac{a}{b} \approx 1.618",
            font_size=32, color=C_GOLD,
        )
        exact = MathTex(
            r"\varphi = \frac{1+\sqrt{5}}{2}",
            font_size=36, color=C_GREEN,
        )
        right_panel = VGroup(phi_lbl, exact).arrange(DOWN, buff=0.55)
        right_panel.move_to(RIGHT * 2.4 + UP * 0.6)

        self.play(Write(phi_lbl), run_time=1.0)
        self.wait(0.6)

        # ── Remainder rectangle — self-similar property ──────────────────
        rem_rect = Rectangle(
            width=W - sq_side, height=H,
            color=C_ORANGE, stroke_width=2.2, fill_opacity=0,
        )
        rem_rect.align_to(rect, RIGHT)
        rem_rect.align_to(rect, UP)

        note = Text("Remove the square — the remainder is also golden!",
                    font_size=19, color=C_ORANGE)
        note.next_to(right_panel, DOWN, buff=0.50)

        self.play(Create(rem_rect), Write(note), run_time=0.9)
        self.wait(1.2)

        # ── Exact closed form ────────────────────────────────────────────
        self.play(Write(exact), run_time=1.0)
        self.wait(2.0)

        self.play(FadeOut(VGroup(hdr, rect, sq, rem_rect,
                                  a_arrow, b_arrow, a_lbl, b_lbl,
                                  phi_lbl, exact, note)))

    # ══════════════════════════════════════════════════════════════════════
    # PART 5 — 3-D GOLDEN SPIRAL
    # ══════════════════════════════════════════════════════════════════════
    def part5_spiral_3d(self):
        self.set_camera_orientation(phi=65 * DEGREES, theta=-50 * DEGREES)

        hdr = Text("STEP 5 — Golden Spiral in 3D",
                   font_size=28, color=C_CYAN, weight=BOLD)
        hdr.to_corner(UL)
        self.add_fixed_in_frame_mobjects(hdr)
        self.play(FadeIn(hdr))

        axes = ThreeDAxes(
            x_range=[-4, 4, 1], y_range=[-4, 4, 1], z_range=[-3, 3, 1],
            x_length=7, y_length=7, z_length=5,
            axis_config={"color": C_DIM, "stroke_opacity": 0.4},
        )
        self.play(Create(axes), run_time=0.8)

        # True logarithmic golden spiral lifted into 3D helix
        # r(θ) = e^(θ * ln(φ) / (π/2))  — grows by φ each quarter turn
        b = np.log(PHI) / (PI / 2)

        spiral1 = ParametricFunction(
            lambda t: np.array([
                np.exp(b * t) * np.cos(t) * 0.55,
                np.exp(b * t) * np.sin(t) * 0.55,
                t * 0.18,
            ]),
            t_range=[-2 * PI, 3.5 * PI, 0.04],
            stroke_width=3.5,
        )
        spiral1.set_color_by_gradient(C_PURPLE, C_CYAN, C_GOLD)

        spiral2 = ParametricFunction(
            lambda t: np.array([
                np.exp(b * t) * np.cos(t) * 0.55,
                np.exp(b * t) * np.sin(t) * 0.55,
                -t * 0.18,
            ]),
            t_range=[-2 * PI, 3.5 * PI, 0.04],
            stroke_width=3.5,
        )
        spiral2.set_color_by_gradient(C_PINK, C_ORANGE, C_GREEN)

        dot = Dot(radius=0.10, color=C_GOLD)

        self.play(Create(spiral1, run_time=3.5), rate_func=linear)
        self.play(Create(spiral2, run_time=3.5), rate_func=linear)

        note = Text("r grows by φ each quarter turn", font_size=22, color=C_GOLD)
        note.to_edge(DOWN, buff=0.45)
        self.add_fixed_in_frame_mobjects(note)
        self.play(Write(note))

        self.begin_ambient_camera_rotation(rate=0.22)
        self.wait(2.8)
        self.move_camera(phi=30 * DEGREES, theta=120 * DEGREES, run_time=2.5)
        self.move_camera(phi=70 * DEGREES, theta=240 * DEGREES, run_time=2.5)
        self.stop_ambient_camera_rotation()

        self.play(FadeOut(VGroup(axes, spiral1, spiral2, note, hdr)))

    # ══════════════════════════════════════════════════════════════════════
    # PART 6 — THE MATHEMATICS
    # ══════════════════════════════════════════════════════════════════════
    def part6_math(self):
        self.set_camera_orientation(phi=0, theta=-PI / 2)

        hdr = Text("STEP 6 — The Mathematics of φ",
                   font_size=30, color=C_CYAN, weight=BOLD).to_corner(UL)
        self.play(FadeIn(hdr))

        eqs = [
            (r"\varphi^2 = \varphi + 1",
             "φ is the only number equal to\nits own square minus 1",
             C_GOLD),
            (r"\varphi = 1 + \cfrac{1}{1+\cfrac{1}{1+\cfrac{1}{\ddots}}}",
             "Infinite continued fraction\n— simplest possible",
             C_CYAN),
            (r"\varphi = \sqrt{1+\sqrt{1+\sqrt{1+\cdots}}}",
             "Infinite nested radicals",
             C_GREEN),
            (r"\lim_{n\to\infty}\frac{F_{n+1}}{F_n} = \varphi",
             "Fibonacci ratio converges to φ",
             C_ORANGE),
        ]

        rows = VGroup()
        for latex, desc, col in eqs:
            eq_mob = MathTex(latex, font_size=34, color=col)
            desc_mob = Text(desc, font_size=17, color=C_DIM)
            sep = DashedLine(LEFT * 0.01, RIGHT * 0.01,
                             stroke_width=0)  # invisible spacer
            row = VGroup(eq_mob, desc_mob).arrange(RIGHT, buff=0.55,
                                                    aligned_edge=UP)
            bg = RoundedRectangle(
                corner_radius=0.14,
                width=row.width + 0.5,
                height=row.height + 0.32,
                fill_color=col, fill_opacity=0.07,
                stroke_color=col, stroke_width=1.2,
            )
            bg.move_to(row)
            rows.add(VGroup(bg, row))

        rows.arrange(DOWN, buff=0.30, aligned_edge=LEFT).center().shift(DOWN * 0.3)

        for r in rows:
            self.play(FadeIn(r, shift=RIGHT * 0.15), run_time=0.60)

        self.wait(2.8)
        self.play(FadeOut(VGroup(hdr, rows)))

    # ══════════════════════════════════════════════════════════════════════
    # PART 7 — φ IN NATURE & APPLICATIONS
    # ══════════════════════════════════════════════════════════════════════
    def part7_nature(self):
        self.set_camera_orientation(phi=0, theta=-PI / 2)

        hdr = Text("φ in Nature & the World",
                   font_size=36, color=C_GOLD, weight=BOLD)
        hdr.to_edge(UP, buff=0.40)

        cards_data = [
            (C_GREEN,  "Sunflower",  "Seed spirals: 34 & 55\nconsecutive Fibonacci"),
            (C_CYAN,   "Nautilus",   "Shell chambers\ngrow by ratio φ"),
            (C_ORANGE, "Galaxies",   "Spiral arms follow\nlogarithmic φ curves"),
            (C_PURPLE, "Art",        "Parthenon, Da Vinci,\nLe Corbusier"),
            (C_PINK,   "DNA",        "34Å × 21Å per full cycle\n— both Fibonacci numbers"),
            (C_GOLD,   "Design",     "Logos, UI grids &\ntype scale ratios"),
        ]

        cards = VGroup()
        for col, title, body in cards_data:
            t = Text(title, font_size=20, color=col, weight=BOLD)
            b = Text(body,  font_size=15, color=C_DIM)
            inner = VGroup(t, b).arrange(DOWN, buff=0.10, aligned_edge=LEFT)
            bg = RoundedRectangle(
                corner_radius=0.16,
                width=inner.width + 0.42,
                height=inner.height + 0.32,
                fill_color=col, fill_opacity=0.11,
                stroke_color=col, stroke_width=1.5,
            )
            bg.move_to(inner)
            cards.add(VGroup(bg, inner))

        cards.arrange_in_grid(rows=2, cols=3, buff=0.30)
        cards.next_to(hdr, DOWN, buff=0.42)
        cards.center()

        # Closing line
        closing = VGroup(
            Text("φ is not just beautiful —", font_size=24,
                 color=C_WHITE),
            Text("it is the mathematics of growth itself.",
                 font_size=24, color=C_GOLD, weight=BOLD),
        ).arrange(RIGHT, buff=0.18)
        closing.to_edge(DOWN, buff=0.42)

        self.play(FadeIn(hdr))
        self.play(LaggedStartMap(FadeIn, cards, shift=UP * 0.25,
                                  lag_ratio=0.14, run_time=1.8))
        self.play(Write(closing), run_time=1.2)
        self.wait(3.2)
        self.play(FadeOut(VGroup(hdr, cards, closing)))

# Commented out IPython magic to ensure Python compatibility.
# %%manim pql  FibonacciGolden --disable_caching